package com.rathanak.khmerroman.spelling_corrector

class EnglishKhmerMap {
    companion object {
        val en2Khmer = mapOf(
            'q' to 'ឆ',
            'w' to 'ឹ',
            'e' to 'េ',
            'r' to 'រ',
            't' to 'ត',
            'y' to 'យ',
            'u' to 'ុ',
            'i' to 'ិ',
            'o' to 'ោ',
            'p' to 'ផ',

            'a' to 'ា',
            's' to 'ស',
            'd' to 'ដ',
            'f' to 'ថ',
            'g' to 'ង',
            'h' to 'ហ',
            'j' to '្',
            'k' to 'ក',
            'l' to 'ល',

            'z' to 'ឋ',
            'x' to 'ខ',
            'c' to 'ច',
            'v' to 'វ',
            'b' to 'ប',
            'n' to 'ន',
            'm' to 'ម',
            ',' to '៊',
            '.' to '។',

            'Q' to 'ឈ',
            'W' to 'ឺ',
            'E' to 'ែ',
            'R' to 'ឬ',
            'T' to 'ទ',
            'Y' to 'ួ',
            'U' to 'ូ',
            'I' to 'ី',
            'O' to 'ៅ',
            'P' to 'ភ',

            'A' to 'ឫ',
            'S' to 'ៃ',
            'D' to 'ឌ',
            'F' to 'ធ',
            'G' to 'អ',
            'H' to 'ះ',
            'J' to 'ញ',
            'K' to 'គ',
            'L' to 'ឡ',

            'Z' to 'ឍ',
            'X' to 'ឃ',
            'C' to 'ជ',
            'V' to 'ៈ',
            'B' to 'ព',
            'N' to 'ណ',
            'M' to 'ំ',

            '1' to '១',
            '2' to '២',
            '3' to '៣',
            '4' to '៤',
            '5' to '៥',
            '6' to '៦',
            '7' to '៧',
            '8' to '៨',
            '9' to '៩',
            '0' to '០',

            '@' to 'ៗ',
            '#' to '៛',
            '$' to '៍',
            '%' to '័',
            '&' to '៏',
            '*' to '៌',
            '-' to '់',
            '=' to '៉',
            '(' to '៖',
            ')' to 'ឧ',
            '!' to 'ឥ',
            '"' to 'ឲ',
            '\'' to 'ឭ',
            ':' to 'ឯ',
            ';' to 'ៀ',
            '\\' to 'ឿ',
            '?' to 'ឿ'
        )
        val kh2English = mapOf(
            'ឆ' to 'q',
            'ឹ' to 'w',
            'េ' to 'e',
            'រ' to 'r',
            'ត' to 't',
            'យ' to 'y',
            'ុ' to 'u',
            'ិ' to 'i',
            'ោ' to 'o',
            'ផ' to 'p',

            'ា' to 'a',
            'ស' to 's',
            'ដ' to 'd',
            'ថ' to 'f',
            'ង' to 'g',
            'ហ' to 'h',
            '្' to 'j',
            'ក' to 'k',
            'ល' to 'l',

            'ឋ' to 'z',
            'ខ' to 'x',
            'ច' to 'c',
            'វ' to 'v',
            'ប' to 'b',
            'ន' to 'n',
            'ម' to 'm',

            'ឈ' to 'Q',
            'ឺ' to 'W',
            'ែ' to 'E',
            'ឬ' to 'R',
            'ទ' to 'T',
            'ួ' to 'Y',
            'ូ' to 'U',
            'ី' to 'I',
            'ៅ' to 'O',
            'ភ' to 'P',

            'ឫ' to 'A',
            'ៃ' to 'S',
            'ឌ' to 'D',
            'ធ' to 'F',
            'អ' to 'G',
            'ះ' to 'H',
            'ញ' to 'J',
            'គ' to 'K',
            'ឡ' to 'L',

            'ឍ' to 'Z',
            'ឃ' to 'X',
            'ជ' to 'C',
            'ៈ' to 'V',
            'ព' to 'B',
            'ណ' to 'N',
            'ំ' to 'M'
        )
    }
}